name: Build Magisk WSA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone
        run: git clone https://github.com/LSPosed/MagiskOnWSALocal.git

      - name: Build
        run: |
          cd MagiskOnWSALocal
          chmod +x scripts/run.sh
          ./scripts/run.sh \
            --arch x64 \
            --release-type RP \
            --gapps pico \
            --root magisk \
            --compress-format zip \
            --skip-download-wsa
