name: Build Magisk WSA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - - name: Clone MagiskOnWSA
  run: |
    git clone https://github.com/LSPosed/MagiskOnWSALocal.git

      - name: Build WSA
        run: |
          cd MagiskOnWSA
          chmod +x scripts/run.sh
          ./scripts/run.sh \
            --arch x64 \
            --release-type stable \
            --gapps pico \
            --root magisk
